### ISSUE TITLE
[Suggestion] Support for custom OAuth providers

### ISSUE THREAD

**Issue by Corban-Lee** [Lynx-Shortener/Lynx#101]
**Is your feature request related to a problem? Please describe.**
The self-hosting ecosystem is large and always growing, an internal authentication system is great for people running one or a few services, but becomes a nuisance when running 5, 10, 20 or more different services, as in that case the user has to maintain an inconvenient amount of passwords. My proposed change could help alleviate this issue on the part of Lynx.

**Describe the solution you'd like**
I'm requesting the support for custom OAuth providers such as Authelia and Authentic, so that people can use single sign-on, and have an overall greater user-experience by reducing the need to remember yet another password, if they choose to configure it. This would also allow for greater security from OAuth providers that integrate 2FA measures such as security keys.

**Describe alternatives you've considered**
It may be easier, if not already implemented, to allow admins to set a user token lifespan, so that it can be changed to a year for example, as a workaround, saving users from entering internally managed passwords multiple times, in the case that they are using an authentication service via proxy for example.

**Additional context**
For me personally, this is a huge inconvenience to have to reach for passwords, especially knowing that I have a single sign-on service with most of my other applications. I've considered looking for alternatives, but I really like Lynx over the competition, and want every excuse to stay.

Implementing this support also allows development to focus less on the authentication side of things, as you could divert users to custom OAuth setup guides, if they demand more security features.

**Comment by JackBailey** [comment]
Hi, thank you for the suggestion. This makes a lot of sense to myself as I have a bunch of services behind Authentik (and I have previously used Authelia).

I'll look into adding this, alongside standard OAuth providers such as GitHub and Google.

**Comment by JackBailey** [comment]
Closed due to #155.
