### ISSUE TITLE
Env var or setting to disable some modal dialogs

### ISSUE THREAD

**Issue by luckman212** [Lynx-Shortener/Lynx#105]
Since there's already a confirmation that pops up before deleting, this extra popup seems unnecessary and just makes it a bit cumbersome. A way to disable them would be awesome!

<img width="678" alt="image" src="https://github.com/Lynx-Shortener/Lynx/assets/1992842/88c1e698-e695-4973-b4c4-378a3931f907">

(same for the **Successfully created your link** popup...)

**Comment by JackBailey** [comment]
Hmm best way would probably be adding a per device site settings page, and "Show confirmation popups" could be a setting on that, would that work for you?

**Comment by luckman212** [comment]
Per device, or per user account? Not sure I understand the logic in it being a per-device setting—but honestly whatever you think makes the most sense logically. I appreciate the response and happy new year!

**Comment by JackBailey** [comment]
I was thinking just per device, as there are plans to add custom colour themes in the future and it'd probably fit in well in the settings next to the above mentioned feature.

Also means that if a user would like the pop-ups enabled on their phone when it's easier to miss-click something, they can.

And yeah, happy new year to you too!

**Comment by JackBailey** [comment]
In the mentioned commit I've added a toggle for this feature, it disables all of the "Successfully...." popups.

It'll be added in 1.8.0 which I'm hoping to release soon, I wouldn't recommend running it just yet but you're welcome to give it a go with :1.8.0-beta in a test docker container.

**Comment by luckman212** [comment]
Sounds great, I'm on the road now but will give that a test pretty soon. Thanks for considering this!

**Comment by luckman212** [comment]
I just had a chance to try that 1.8.0 beta 

Looking very nice!

The feature to reduce the popups is working great. 

Just 2 little things I noticed:

1. The switch looks reversed, or upside down or whatever. Off is on and on is off... screenshot:

![screenshot_rdnWTvSb](https://github.com/Lynx-Shortener/Lynx/assets/1992842/0d0c1ab1-c2c6-4500-b781-07addbfc7ea5)

2. The little (account switcher?) popup has my account and then a "blank" account checked off, seems like an index is off by one or something

![screenshot_1WAu2pp9](https://github.com/Lynx-Shortener/Lynx/assets/1992842/8d3fe764-2c70-4516-973c-a54ace5c28cf)

**Comment by JackBailey** [comment]
Glad it works well for you.

1. I wasn't completely sure of the best way to orient the toggle, but right, towards the text it's turning on probably makes the most sense.

2. Ahh yeah that filters links by user, I'll look into fixing it and maybe making its use a bit more clear

**Comment by luckman212** [comment]
Only other thing I noticed so far is the **Add Link** button could use some more padding along the right edge of the view.

![CleanShot 2024-01-02 at 13 56 09](https://github.com/Lynx-Shortener/Lynx/assets/1992842/2db7470d-70c6-4db4-9d97-527abc86f0d9)

**Comment by JackBailey** [comment]
I've fixed both of the above issues. 

The user filter was a bit unclear, that top one filters by all available users. It now says "All users" - UX isn't quite my speciality 😆

**Comment by luckman212** [comment]
Just pulled a fresh 1.8.0-beta, looking good!
