### ISSUE TITLE
Button to copy short URL

### ISSUE THREAD

**Issue by luckman212** [Lynx-Shortener/Lynx#109]
I may be missing it somewhere, but I wonder is there supposed to be a "copy URL" button in the UI somewhere to grab the link to the shortened URL? As it is, it seems the only way to do it is to right-click on the "slug" column link and then use the browser's "Copy Link Address" command.

This is fine but it's a bit of a chore - a simple "copy" button would be convenient (or if you don't want to clutter the UI, you could hide it in the 3 dots at the right of the row)

I'm currently running the 1.8.0-beta track, fyi

**Comment by JackBailey** [comment]
Hi, I've added this to the 1.8.0 beta, let me know what you think :)

**Comment by luckman212** [comment]
Took me a minute to figure out that the "slug" was clickable, but ... nice! I like it 🎉
