### ISSUE TITLE
TLD's which are longer than 6 chars return false even though correct domain

### ISSUE THREAD

**Issue by benni347** [Lynx-Shortener/Lynx#112]
**Bug Description**
There is an issue with the validation of top-level domains (TLDs) that exceed six characters in length. For instance, the URL <https://spiezer.restaurant/restaurant> is valid, yet it is erroneously flagged as invalid due to its 11-character TLD.

**Steps to Reproduce**
To replicate this behavior:
1. Access the Lynx dashboard.
2. Attempt to shorten the URL `https://spiezer.restaurant/restaurant`.

**Expected Behavior**
The expectation is that the URL would be successfully shortened without triggering an error message stating Invalid destination URL format, acknowledging its validity.

**Desktop Configuration**
1. Operating Systems: Linux and macOS
2. Browsers: Firefox, Chrome
3. Version: 1.7.4

**Additional Context**
The validation logic for URLs should accommodate TLDs that are longer than six characters. The problematic code can be found here: [URL validation check in code](https://github.com/Lynx-Shortener/Lynx/blob/6bfe90422d899723b6c8a9051a291c01613d868a/src/db/modules/valid/url.js#L3C80-L3C98).

**Comment by JackBailey** [comment]
Ahh yep I'll need to fix that and will release the change soon.

In the meantime, you should be able to use URL_REGEX to override this: https://docs.getlynx.dev/installation/environment-variables#other
