### ISSUE TITLE
Support for SQLite

### ISSUE THREAD

**Issue by aminnairi** [Lynx-Shortener/Lynx#148]
**Is your feature request related to a problem? Please describe.**
The docs suggest using a MongoDB database, which suppose you cannot use another database-as-a-file like SQLite.

**Describe the solution you'd like**
Allow the use of a SQLite database instead of MongoDB.

**Describe alternatives you've considered**
None.

**Additional context**
This would be great for lightening up the server if concurrency and locks are not a problem.

**Comment by JackBailey** [comment]
Thanks for your suggestion, this is something I'd be interested in, especially as it'd make deployment easier. I have switching to a SQL-based database on the [roadmap](https://github.com/orgs/Lynx-Shortener/projects/2?pane=issue&itemId=27149892), I'm just very busy with other things currently so it takes me a while to get around to things. I'll definitely try to do this at some point though :)

**Comment by aminnairi** [comment]
Are you okay accepting pull request from non-core contributors? I could add Sequelize Models besides the ones you created for MongoDB such that you can slowly migrate to SQL-like database.

Let me know, I can find some time this week to propose some changes.

**Comment by JackBailey** [comment]
Yeah definitely, that'd be great

**Comment by JackBailey** [comment]
Closed due to #155.
