### ISSUE TITLE
Password does not match requirements

### ISSUE THREAD

**Issue by altendorfme** [Lynx-Shortener/Lynx#150]
Password validation when creating a user does not work correctly:

Example: `#Yq3zmdcex*G3F`

It will always alert with Password does not match requirements

- Docker Lynx 1.9.2

**To Reproduce**
1. Go to User Management
2. Click on Add User
3. Fill password

**Screenshots**
![image](https://github.com/Lynx-Shortener/Lynx/assets/1530032/a4e3230e-2cae-40d8-ab80-c11a74bb22e9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 125

**Comment by JackBailey** [comment]
Should be fixed in 1.10.1
