### ISSUE TITLE
Add option for bypassing destination regex

### ISSUE THREAD

**Issue by calli33** [Lynx-Shortener/Lynx#70]
A feature on bypass url check then support url schema would be great. it helps to shortlink to open an App on iOS.

**Comment by JackBailey** [comment]
Thanks for the feature request. I'll try to get to adding this feature.

I'll either add an environment variable to override the existing regex for link destinations (and potentially password too) which would probably be the best option securitywise too as obviously you don't want every URL available (such as interacting with network devices or bugged URLs). 

Alternatively I'll just add an option to disable the regex all together, but it'd be at the user's own risk.

**Comment by calli33** [comment]
Cheers!! Look forward..

**Comment by JackBailey** [comment]
Oh, also for your ARM64 request via Reddit, please create a separate issue.

**Comment by JackBailey** [comment]
Just running some checks but seems to be working okay. It's on `jackbailey/lynx:1.6.0-beta` if you want to give it a go. 

Docs are here: https://docs.getlynx.dev/installation/environment-variables#other
