### ISSUE TITLE
ARM64 docker support

### ISSUE THREAD

**Issue by calli33** [Lynx-Shortener/Lynx#72]
Want this great tool to launch in arm-based Oracle A1.Flex.

**Comment by JackBailey** [comment]
@calli33, support for arm64 is being added in 1.7.1, being released soon. Please could you test if jackbailey/lynx:1.7.1-beta works for you? Seems to on my oracle arm vps.

**Comment by calli33** [comment]
Hi @JackBailey  it can be run on my Oracle ARM VPS.
However, when I tried to import links from the csv generated by previous lynx, it shows Internal Server Error when importing links.

For the log:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /app/src/api/import.js:55:65
    at Array.filter (<anonymous>)
    at /app/src/api/import.js:55:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by JackBailey** [comment]
Found the error and committed it to 1.7.1 - 573b7263fcb65265b3a63901a2bad189d3316492.

The builds take ages (36 min) using github actions when building for arm64 so I'll look into an alternative but you should be able to give it a go in 20 minutes or so.

**Comment by calli33** [comment]
Great, it works. 
Thanks!

**Comment by JackBailey** [comment]
Will be added in [1.7.1](https://github.com/Lynx-Shortener/Lynx/pull/83), ETA is within the next couple days
