### ISSUE TITLE
[Suggestion] CLI

### ISSUE THREAD

**Issue by JackBailey** [Lynx-Shortener/Lynx#90]
Create a multi-platform CLI, (Windows + *nix) for creating URLs easily, and maybe updating them.

Requested in #86

**Comment by Supernova3339** [comment]
If you want, I'd be happy to do this for you. I've made a CLI for discordextras ( internal tool ) that is multiplatform. It's Javascript based, but it's AIO and works out of the box. I'll have to tweak some things to make it work with Lynx however. Let me know if your interested!

Cheers, SuperDev

**Comment by JackBailey** [comment]
Hi, that'd be amazing - thank you SuperDev.

API docs are at https://docs.getlynx.dev/api/usage

And I've added you to Lynx-Shortener/CLI

When I'm next free I'll take a look to understand how you've done it so I should be able to maintain + bug fix it too.

**Comment by Supernova3339** [comment]
> Hi, that'd be amazing - thank you SuperDev.
> 
> API docs are at https://docs.getlynx.dev/api/usage
> 
> And I've added you to Lynx-Shortener/CLI
> 
> When I'm next free I'll take a look to understand how you've done it so I should be able to maintain + bug fix it too.

awesome, if your comfortable I can send you the code for discordextras CLI if you want an idea on how things work.

**Comment by JackBailey** [comment]
Sounds good, thank you

**Comment by Supernova3339** [comment]
> Sounds good, thank you

is there a private way I am able to send it to you?

**Comment by Supernova3339** [comment]
> Hi, that'd be amazing - thank you SuperDev.
> 
> API docs are at https://docs.getlynx.dev/api/usage
> 
> And I've added you to Lynx-Shortener/CLI
> 
> When I'm next free I'll take a look to understand how you've done it so I should be able to maintain + bug fix it too.

seems like you added me to the wrong repository haha, on the main one instead of the CLI one. I'd add something here if I wasn't too busy with Easyshortener. Redesigned a bunch of stuff, even added a command bar.

**Comment by JackBailey** [comment]
You could probably zip it and email it to info [at ] getlynx.dev or a Google drive link or something

**Comment by Supernova3339** [comment]
> You could probably zip it and email it to info [at ] getlynx.dev or a Google drive link or something

would a wormhole link work for you?

**Comment by JackBailey** [comment]
Yep that'd work well, thank you. I'm currently away for the next week so won't be able to take a look until I get back but I'll make sure to then.

**Comment by Supernova3339** [comment]
> Yep that'd work well, thank you. I'm currently away for the next week so won't be able to take a look until I get back but I'll make sure to then.

No worries! If you could give me access to the /CLI repo instead of /Lynx so I can git all changes  would be appreciated.

Link expires in 60 mins: <https://wormhole.app/JzDAB#CUHKRMHdnk1KdABjNhOMKg>

**Comment by Supernova3339** [comment]
I'll try to finish the CLI in a few hours.

**Comment by Supernova3339** [comment]
One thing I didn't notice is the authentication part. The other thing I'm wondering is if you want a workflow via github actions to build it automatically for all platforms.

**Comment by JackBailey** [comment]
Oh yep, oops. There you go you should be able to access /CLI now - I also downloaded the zip from the link. Thank you

**Comment by JackBailey** [comment]
> One thing I didn't notice is the authentication part. The other thing I'm wondering is if you want a workflow via github actions to build it automatically for all platforms.

I've been moving to Drone CI/CD recently so I'd probably look into that myself instead but if you have an existing workflow I'd greatly appreciate it

**Comment by Supernova3339** [comment]
> Oh yep, oops. There you go you should be able to access /CLI now - I also downloaded the zip from the link. Thank you

Forgot to mention, if you want to compile it I used ncc and babel, it's preconfigured so shouldn't need to worry but ncc and pkg should be global. ( this is for all platforms)

**Comment by Supernova3339** [comment]
one final tiny thing so I can be transparent about any changes, if you can add a roadmap to the repository would be good, noticed that Lynx has one, might as well continue it

**Comment by Supernova3339** [comment]
> > One thing I didn't notice is the authentication part. The other thing I'm wondering is if you want a workflow via github actions to build it automatically for all platforms.
> 
> I've been moving to Drone CI/CD recently so I'd probably look into that myself instead but if you have an existing workflow I'd greatly appreciate it

Workflow is added, errors due to permissons it needs to push.

**Comment by JackBailey** [comment]
Apologies for not getting back to you on this. I'll try to find some time on this soon to properly look through what you've done and release it.

**Comment by JackBailey** [comment]
Closed due to #155.
