### ISSUE TITLE
[Suggestion] Add a filter to sort links by link author

### ISSUE THREAD

**Issue by 6gh** [Lynx-Shortener/Lynx#91]
**Is your feature request related to a problem? Please describe.**
When an Admin or an Owner logs into the overview page, they see all links created across all the users. If there are many links, it'll be hard for the admins to monitor just their links. 

For example, imagine each of 10 users have 10 links made, and an admin wants to edit one of their links. It could be difficult to find their links from the 100 links present on their overview page.

**Describe the solution you'd like**
An option to be present for Admins and Owners that will only show links they created. The option could be a small tick box with the text, "Show your links only"

Alternatively, there can also be a "Filter" button next to the search button to perhaps show a dialog with the tick box in there, which would also be useful for the future if you ever need to have more filter options.

**Describe alternatives you've considered**
I've tried just putting the admin name in the search bar, but it doesn't filter out links other users have created.

**Comment by JackBailey** [comment]
Sounds like a great feature, will add in 1.8.0, probably as a button next to the search box that'll allow you to select what user's links to view.
