### ISSUE TITLE
[Question] Is it possible to create a default user that automatically logs in?

### ISSUE THREAD

**Issue by suvis1** [Lynx-Shortener/Lynx#92]
Hi!

So ive been searching for a link shortener that me and a couple of my colleagues can use for work, and was just wondering if the titles question is possible? I would be using Cloudflare Zero Trust to expose this instance to the public, adding MFA for /dash and /api , so i dont think having accounts is necessary for my use case?

It would be easier if i could just add users to Zero Trust and they all get access to the same Lynx "account".

Thank you beforehand for any response <3

**Comment by JackBailey** [comment]
It's not currently implemented but I'll have a look into adding it as I definitely see a use for it

**Comment by JackBailey** [comment]
Added in [1.8.0](https://github.com/Lynx-Shortener/Lynx/commit/35d6741fc8be958dc0e80918bda7ca8f14bbd966).

Requires SOLE_USER to be set to the user's ID, and for the user to set the below setting. Therefore both the server and the user need to agree they want this to be enabled.
If any endpoints that require authentication are accessed and no cookie is provided, it'll create the cookie and apply it to the current request.

<img width="747" alt="image" src="https://github.com/Lynx-Shortener/Lynx/assets/81699395/1778fd7d-5c74-4847-bd9f-5c3afeab8daf">
