### ISSUE TITLE
MongoDB 5.0+ requires a CPU with AVX support

### ISSUE THREAD

**Issue by Tataukee** [Lynx-Shortener/Lynx#99]
Maybe it's time to switch to MariaDB ? 
Any suggestions to avoid the error in title ?

**Comment by JackBailey** [comment]
You could try version 4.4, looks like its still supported for the next few months, should give me enough time to work out a proper solution.

MariaDB _is_ on the roadmap, I just need to find time for it as it's quite a big change.

**Comment by Tataukee** [comment]
Thank you jack . I will try that 👍

**Comment by JackBailey** [comment]
Any luck?

**Comment by JohannCR** [comment]
Same problem here... Using mongo 4.4 does not work either. Any tips ?

**Comment by JackBailey** [comment]
> Same problem here... Using mongo 4.4 does not work either. Any tips ?

Would be fixed by #148 which would add SQL support, I'm guessing mongo 4.4 doesn't work as it's no longer supported.
